/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author david
 */
public class ifrm_ayuda extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrm_ayuda
     */
    public ifrm_ayuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(51, 51, 51));
        setClosable(true);
        setMaximizable(true);

        jTextArea1.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Ayuda:\n1. Para escribir en la calculadora puede usar\nel teclado que aparece en la pantalla\npresionando los botones de programa.\n\n2. También puede escribir desde su teclado\nfísico, pero el programa solo aceptará \nteclas númericas.\n\n3. Para obtener el resultado puede presionar\nla tecla enter o la combinación de teclas\n\"shift + 0\", o bien desde la tecla \"=\"  que\naparece en pantalla\n\n4. Las divisiones entre 0 serán tomadas como\ninvalidas.\n\n5. La opción \"Opciones\" que se encuentra\nen la parte superior izquierda de la ventana\nle ofrecera dos posibilidades:\n\n  a) Nuevo: reinicia la calculadora en 0\n  y señala en el registro que es una nueva\n  operación.\n\n  b) Historial: muestra el registro de \n  operaciones que se han realizado. ");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
